{{- if and .Values.controllerManager.enable .Values.controllerManager.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kubeedge-controller-manager
  namespace: {{ .Release.Namespace }}
  {{- with .Values.controllerManager.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: {{ .Values.controllerManager.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- with .Values.controllerManager.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
